# Use the official Miniconda3 image
FROM continuumio/miniconda3

# Set the working directory
WORKDIR /app

# Copy the environment.yml to the working directory
COPY environment.yml .

# Update conda and ensure the classic solver is set
RUN conda update conda -n base -c defaults && \
    conda config --set solver classic

# Install the conda environment
RUN conda env create -f environment.yml

# Make RUN commands use the new environment
SHELL ["conda", "run", "-n", "face-recognition-app", "/bin/bash", "-c"]

# Install system dependencies for OpenCV
COPY packages.txt .
RUN apt-get update && xargs apt-get install -y < packages.txt

# Copy the current directory contents into the container
COPY . .

# Activate the environment
RUN echo "conda activate face-recognition-app" > ~/.bashrc
ENV PATH /opt/conda/envs/face-recognition-app/bin:$PATH

# Run the Streamlit app
CMD ["streamlit", "run", "FaceRecogAtt/with_interface.py"]
